# Generated by Django 6.0.4 on 2026-04-26 23:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('examens', '__first__'),
        ('professeurs', '__first__'),
        ('salles', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='Surveillance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('examen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='examens.examen')),
                ('professeur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='professeurs.professeur')),
                ('salle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='salles.salle')),
            ],
        ),
    ]
