# Generated by Django 6.0.4 on 2026-05-08 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='nom_admin',
            field=models.CharField(blank=True, default='', max_length=200, verbose_name='رئيس مركز الامتحان'),
        ),
    ]
