# Generated by Django 6.0.4 on 2026-05-27 19:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Professeur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identifiant_unique', models.CharField(blank=True, default='', max_length=20)),
                ('nom', models.CharField(max_length=200)),
                ('specialite', models.CharField(max_length=200)),
                ('institution', models.CharField(blank=True, default='', max_length=255)),
                ('telephone', models.CharField(blank=True, default='', max_length=20)),
                ('centre', models.ForeignKey(limit_choices_to={'role': 'directeur'}, on_delete=django.db.models.deletion.CASCADE, related_name='superviseurs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['nom', 'id'],
                'unique_together': {('centre', 'identifiant_unique')},
            },
        ),
    ]
