# Generated by Django 6.0.4 on 2026-05-27 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('professeurs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='professeur',
            name='sexe',
            field=models.CharField(blank=True, choices=[('M', 'ذكر'), ('F', 'أنثى')], default='', max_length=1),
        ),
    ]
