# Generated by Django 6.0.4 on 2026-04-26 23:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Matiere',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Salle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.PositiveSmallIntegerField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='salles', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('numero', 'user')},
            },
        ),
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sections', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Serie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='series', to='exam_planning.section')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='series', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Session',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=50)),
                ('jours', models.JSONField(default=list)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Examen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('heure_debut', models.TimeField()),
                ('heure_fin', models.TimeField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('matiere', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exam_planning.matiere')),
                ('salle', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='exam_planning.salle')),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exam_planning.section')),
                ('serie', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='exam_planning.serie')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='examens', to='exam_planning.session')),
            ],
        ),
        migrations.CreateModel(
            name='Candidat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num_ins', models.CharField(max_length=20)),
                ('nom_prenom', models.CharField(max_length=255)),
                ('ncin', models.CharField(blank=True, max_length=20)),
                ('section', models.CharField(blank=True, max_length=100)),
                ('etablissement', models.CharField(blank=True, default='', max_length=255)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='candidats', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'num_ins')},
            },
        ),
        migrations.CreateModel(
            name='MatiereSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('heures', models.PositiveSmallIntegerField(default=2)),
                ('matiere', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sections_durees', to='exam_planning.matiere')),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matieres_durees', to='exam_planning.section')),
            ],
            options={
                'unique_together': {('matiere', 'section')},
            },
        ),
        migrations.CreateModel(
            name='Inscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num_ins', models.CharField(max_length=20)),
                ('nom_prenom', models.CharField(max_length=255, verbose_name='الإسم و اللقب')),
                ('cin', models.CharField(blank=True, max_length=20, null=True, verbose_name='رقم بطاقة التعريف الوطنية')),
                ('section', models.CharField(max_length=100, verbose_name='الشعبة')),
                ('etablissement', models.CharField(blank=True, default='', max_length=255, verbose_name='المعهد')),
                ('serie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inscriptions', to='exam_planning.serie')),
            ],
            options={
                'unique_together': {('serie', 'num_ins')},
            },
        ),
    ]
