# Generated by Django 6.0.4 on 2026-05-05 23:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam_planning', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='matiere',
            name='type',
            field=models.CharField(choices=[('obligatoire', 'إجبارية'), ('optionnelle', 'اختيارية')], default='obligatoire', max_length=20),
        ),
        migrations.AlterField(
            model_name='matieresection',
            name='heures',
            field=models.FloatField(default=2),
        ),
    ]
