# Generated by Django 6.0.4 on 2026-05-08 23:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam_planning', '0002_matiere_type_alter_matieresection_heures'),
    ]

    operations = [
        migrations.AlterField(
            model_name='matiere',
            name='nom',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterUniqueTogether(
            name='matiere',
            unique_together={('nom', 'type')},
        ),
    ]
