# Generated by Django 6.0.4 on 2026-05-09 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam_planning', '0003_alter_matiere_nom_alter_matiere_unique_together'),
    ]

    operations = [
        migrations.CreateModel(
            name='TemplateMatiere',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('matieres', models.JSONField(default=list)),
                ('matiere_sections', models.JSONField(default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'قالب المواد',
                'verbose_name_plural': 'قالب المواد',
            },
        ),
    ]
