# Generated by Django 6.0.4 on 2026-05-10 08:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam_planning', '0004_template_matiere'),
        ('professeurs', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExamenSalle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('examen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='affectations', to='exam_planning.examen')),
                ('salle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exam_planning.salle')),
                ('serie', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='exam_planning.serie')),
                ('surveillant_1', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='surveillances_1', to='professeurs.professeur')),
                ('surveillant_2', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='surveillances_2', to='professeurs.professeur')),
            ],
            options={
                'unique_together': {('examen', 'salle', 'serie')},
            },
        ),
    ]
