# Generated by Django 6.0.4 on 2026-05-11 23:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam_planning', '0005_examen_salle'),
    ]

    operations = [
        migrations.AddField(
            model_name='examen',
            name='candidat_assignments',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
