# Generated by Django 6.0.4 on 2026-05-13 23:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam_planning', '0006_examen_candidat_assignments'),
        ('professeurs', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='SurveillancePlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('total_profs', models.PositiveIntegerField(default=0)),
                ('group_size', models.PositiveIntegerField(default=0)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='surveillance_plans', to='exam_planning.session')),
            ],
            options={
                'verbose_name': 'خطة الحراسة',
                'verbose_name_plural': 'خطط الحراسة',
            },
        ),
        migrations.CreateModel(
            name='SurveillanceAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('session_number', models.PositiveSmallIntegerField(help_text='رقم الحصة (1 أو 2)')),
                ('time_start', models.TimeField(blank=True, null=True)),
                ('time_end', models.TimeField(blank=True, null=True)),
                ('salle_numero', models.PositiveIntegerField(blank=True, help_text='رقم القاعة (بدون FK)', null=True)),
                ('salle_label', models.CharField(blank=True, default='', max_length=50)),
                ('type', models.CharField(choices=[('surveillant', 'مراقب'), ('suppleant', 'احتياط')], default='surveillant', max_length=20)),
                ('group_number', models.PositiveSmallIntegerField(default=1, help_text='رقم المجموعة (1 أو 2)')),
                ('heures', models.FloatField(default=0, help_text='عدد ساعات هذه الحراسة')),
                ('professeur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='surv_assignments', to='professeurs.professeur')),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='exam_planning.surveillanceplan')),
            ],
            options={
                'verbose_name': 'تعيين حراسة',
                'verbose_name_plural': 'تعيينات الحراسة',
                'ordering': ['date', 'session_number', 'salle_numero'],
            },
        ),
    ]
