# Generated by Django 6.0.4 on 2026-05-24 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam_planning', '0007_surveillanceplan_surveillanceassignment'),
    ]

    operations = [
        migrations.CreateModel(
            name='TemplateExamen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('examens', models.JSONField(default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'قالب الامتحانات',
                'verbose_name_plural': 'قالب الامتحانات',
            },
        ),
    ]
