# Generated by Django 6.0.4 on 2026-05-25 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam_planning', '0010_templateexamen_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='examensalle',
            name='layout',
            field=models.CharField(blank=True, default='15', max_length=2),
        ),
    ]
