# Generated by Django 6.0.4 on 2026-05-26 17:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam_planning', '0011_examensalle_layout'),
    ]

    operations = [
        migrations.CreateModel(
            name='SurveillanceGroupConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group1_ids', models.JSONField(default=list)),
                ('group2_ids', models.JSONField(default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exam_planning.session', unique=True)),
            ],
            options={
                'verbose_name': 'تكوين المجموعات',
                'verbose_name_plural': 'تكوينات المجموعات',
            },
        ),
    ]
