# Generated by Django 6.0.4 on 2026-05-30 21:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam_planning', '0012_surveillance_group_config'),
        ('professeurs', '0002_professeur_sexe'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProfessorSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('session1_type', models.CharField(blank=True, default='', help_text='surveillant / suppleant', max_length=20)),
                ('session1_start', models.TimeField(blank=True, null=True)),
                ('session1_end', models.TimeField(blank=True, null=True)),
                ('session1_salle', models.PositiveIntegerField(blank=True, null=True)),
                ('session2_type', models.CharField(blank=True, default='', help_text='surveillant / suppleant', max_length=20)),
                ('session2_start', models.TimeField(blank=True, null=True)),
                ('session2_end', models.TimeField(blank=True, null=True)),
                ('session2_salle', models.PositiveIntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('professeur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_schedules', to='professeurs.professeur')),
            ],
            options={
                'verbose_name': 'برنامج أستاذ',
                'verbose_name_plural': 'برامج الأساتذة',
                'ordering': ['date', 'professeur'],
                'unique_together': {('professeur', 'date')},
            },
        ),
    ]
