# Generated by Django 4.2.30 on 2026-06-23 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam_planning', '0014_controleconfig'),
    ]

    operations = [
        migrations.AddField(
            model_name='inscription',
            name='resultat',
            field=models.CharField(blank=True, choices=[('admis', 'مقبول'), ('controle', 'مراقبة'), ('refuse', 'مرفوض')], default='', max_length=20, verbose_name='النتيجة'),
        ),
    ]
