# Generated by Django 4.2.30 on 2026-06-24 15:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exam_planning', '0015_add_resultat_to_inscription'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inscription',
            name='resultat',
        ),
    ]
